Disable the other test

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -82,35 +82,35 @@ jobs:
           sha: ${{ github.event.pull_request.head.sha }}
           target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
 
-  run-maven-tests:
-
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Check out the repo
-        uses: actions/checkout@v4
-
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '17'
-          cache: maven
-
-      - name: Set up Chrome
-        uses: browser-actions/setup-chrome@latest
-
-      - name: Get Chrome version
-        run: chrome --version
-
-      - name: Run tests with Maven
-        run: ./mvnw clean test
-
-      - name: Generate test report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: maven-test-results
-          path: target/surefire-reports/TEST-*.xml
-          reporter: java-junit
-          fail-on-error: true
+#  run-maven-tests:
+#
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Check out the repo
+#        uses: actions/checkout@v4
+#
+#      - name: Set up JDK 17
+#        uses: actions/setup-java@v4
+#        with:
+#          distribution: 'temurin'
+#          java-version: '17'
+#          cache: maven
+#
+#      - name: Set up Chrome
+#        uses: browser-actions/setup-chrome@latest
+#
+#      - name: Get Chrome version
+#        run: chrome --version
+#
+#      - name: Run tests with Maven
+#        run: ./mvnw clean test
+#
+#      - name: Generate test report
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: maven-test-results
+#          path: target/surefire-reports/TEST-*.xml
+#          reporter: java-junit
+#          fail-on-error: true
